import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	// Redirects @webex/http-core's browser transport away from a bare `new
	// XMLHttpRequest()` (fully subject to the Obsidian renderer's CORS
	// enforcement) to Signalstone's requestUrl-backed shim (which is not,
	// since requestUrl routes through Electron's main process). Scoped to
	// this one dependency's bundled code only — does not touch Obsidian's
	// real `window.XMLHttpRequest`. See src/realtime/RequestUrlXhrShim.ts
	// and docs/WEBEX_CAPABILITIES.md for the full explanation.
	define: {
		XMLHttpRequest: 'window.__signalstoneWebexXhrShim',
	},
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	metafile: prod,
});

if (prod) {
	const result = await context.rebuild();
	if (result.metafile) {
		const text = await esbuild.analyzeMetafile(result.metafile);
		console.log(text);
	}
	await context.dispose();
	process.exit(0);
} else {
	await context.watch();
}
